# Copyright 2025 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM alpine:latest

# 安装OpenSSL
RUN apk add --no-cache openssl bash

# 复制证书生成脚本
COPY generate-certs.sh /generate-certs.sh
RUN chmod +x /generate-certs.sh

# 创建证书目录
RUN mkdir -p /tmp/certs

CMD ["/generate-certs.sh"]
